name: Verifica frase do Itaú Clube

on:
  schedule:
    - cron: '0 * * * *'  # Roda de 1h em 1h
  workflow_dispatch:

jobs:
  check_phrase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instala certificados CA
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instala dependências
        run: pip install requests

      - name: Executa verificação
        env:
          TELEGRAM_BOT_TOKEN2: ${{ secrets.TELEGRAM_BOT_TOKEN2 }}
          TELEGRAM_CHAT_ID2: ${{ secrets.TELEGRAM_CHAT_ID2 }}
        run: python itau.py
